services:
  worker:
    volumes:
      - ./third_party/piper/bin/piper:/usr/local/bin/piper:ro
      - ./third_party/piper/lib:/usr/local/lib/piper:ro
      - ./models/piper/en:/app/voices/en:ro
    environment:
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"
      # Storage (dùng hostname service minio trên network docker)
      STORAGE_KIND: s3
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: tts-vtn
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_FORCE_PATH_STYLE: "1"
      PIPER_CMD: /usr/local/bin/piper
      PIPER_VOICE: /app/voices/en/en_US-amy-medium.onnx
      LD_LIBRARY_PATH: /usr/local/lib/piper
      PATH: /opt/py/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # HQ profile Day-7
      HQ_ENABLED: "true"
      QC_OVERRIDE_DEV: "true"    # Cho HQ lệch vẫn finalize=done + warnings
      TRUEPEAK_OVERSAMPLE: "4"   # 1/2/4/8; ngoài set -> về 4
      TARGET_LUFS: "-16"
      LUFS_TOL: "1.0"            # vẫn 1.0; override sẽ “cứu”
      TRUEPEAK_MAX_DBTP: "-1.0"

  api:
    environment:
      STORAGE_KIND: s3
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: tts-vtn
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_FORCE_PATH_STYLE: "1"

  frontend:
    build: ./apps/frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE}     # http://localhost:4000
    depends_on:
      - api
    ports: ["${FRONTEND_PORT}:3000"]
