services:
  redis:
    image: redis:7-alpine
    container_name: tts-vtn-redis-1
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./apps/api
    env_file: [.env]
    environment:
      - API_PORT=${API_PORT}              # 4000
      - REDIS_URL=${REDIS_URL}            # redis://redis:6379/0
      - STORAGE_ROOT=${STORAGE_ROOT}
      - QUEUE_TTS_BLOCK=${QUEUE_TTS_BLOCK}
      - QUEUE_CONCURRENCY=${QUEUE_CONCURRENCY}
      - API_INLINE_WORKER=0               # không chạy worker trong API
      - TZ=${TZ}

    volumes: [ "./storage:/data/storage" ]
    depends_on:
      redis:
        condition: service_healthy
    ports: ["${API_PORT}:4000"]           # map 4000 ra host

  frontend:
    build: ./apps/frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE}     # http://localhost:4000
    depends_on:
      - api
    ports: ["${FRONTEND_PORT}:3000"]

  worker:
    build: ./apps/worker                   # <— Node worker
    env_file: [.env]
    environment:
      - REDIS_URL=${REDIS_URL}
      - STORAGE_ROOT=${STORAGE_ROOT}
      - ENGINE_DEFAULT=${ENGINE_DEFAULT}
      - PIPER_MODEL=${PIPER_MODEL}
      - PIPER_VOICE_ID=${PIPER_VOICE_ID}
      - QUEUE_TTS_BLOCK=${QUEUE_TTS_BLOCK}
      - QUEUE_CONCURRENCY=${QUEUE_CONCURRENCY}
      - TZ=${TZ}
      - PYTHONPATH=/app/apps/worker
    volumes:
      - ./storage:/data/storage
      - ./models:/models
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    # không cần expose cổng vì không phục vụ HTTP
