name: CI Day8

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=3s
          --health-retries=5

    env:
      REDIS_URL: redis://localhost:6379
      STORAGE_KIND: s3
      S3_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: tts-vtn
      API_PORT: 4000
      VITE_API_BASE: http://localhost:4000
      ENGINE_DEFAULT: piper
      HQ_TOGGLE: "true"
      MINIO_IMAGE: quay.io/minio/minio:latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20 + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - name: Enable corepack + install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install workspace dependencies
        run: pnpm -w install --frozen-lockfile

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install worker dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r apps/worker/requirements.txt

      - name: Start MinIO (official)
        run: |
          docker pull "${MINIO_IMAGE}"
          docker run -d --name minio \
            -p 9000:9000 -p 9001:9001 \
            -e MINIO_ROOT_USER="${S3_ACCESS_KEY}" \
            -e MINIO_ROOT_PASSWORD="${S3_SECRET_KEY}" \
            "${MINIO_IMAGE}" server /data --console-address ":9001"
          for i in {1..30}; do
            if curl -sf http://localhost:9000/minio/health/live >/dev/null; then
              echo "MinIO is live"
              break
            fi
            echo "…waiting MinIO ($i/30)"
            sleep 2
          done

      - name: Create bucket (idempotent)
        run: |
          pip install minio
          python - <<'PY'
          from minio import Minio
          import os, time

          client = Minio(
              "localhost:9000",
              access_key=os.getenv("S3_ACCESS_KEY"),
              secret_key=os.getenv("S3_SECRET_KEY"),
              secure=False,
          )
          bucket = os.getenv("S3_BUCKET", "tts-vtn")
          for _ in range(30):
              try:
                  if not client.bucket_exists(bucket):
                      client.make_bucket(bucket)
                  print("Bucket ready:", bucket)
                  break
              except Exception:
                  time.sleep(1)
          PY

      - name: PyTest (ops/tests)
        run: pytest -q ops/tests

      - name: Build API
        working-directory: apps/api
        run: pnpm build

      - name: Build Frontend
        working-directory: apps/frontend
        run: pnpm build

      - if: always()
        name: Stop MinIO
        run: docker stop minio || true
